In [1]:
# A[2,3] -> Linha 2, Coluna 3

In [2]:
# A[0, :] -> Todo conteúdo da linha 0

In [3]:
# A[:, 0] -> Todo conteúdo da coluna 0

In [4]:
import numpy as np

In [5]:
# np.reshape(*,*, 'C') -> Popula primeiro as linhas -> DEFAULT

In [6]:
# np.reshape(*,*, 'F') -> Popula primeiro as colunas

In [7]:
# np.array() -> Insere linhas inteiras em uma matriz

In [9]:
myData = np.arange(0,20)
print(myData)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [12]:
mat1 = np.reshape(myData, (5,4)) # 5 linhas, 4 colunas 

In [13]:
print(mat1)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]


In [17]:
print(mat1[2,2])

10


In [18]:
mat2 = np.reshape(myData, (5,4), order = 'F')

In [19]:
print(mat2)

[[ 0  5 10 15]
 [ 1  6 11 16]
 [ 2  7 12 17]
 [ 3  8 13 18]
 [ 4  9 14 19]]


In [21]:
print(mat2[2,2])

12


In [24]:
# Conceito POO: myData é um objeto e possui os métodos de np
type(myData)

numpy.ndarray

In [25]:
myData.reshape((5,4))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

---

In [26]:
r1 = ["S", "R", "N"]
r2 = [1,1,1]
r3 = ["F", "L", "A"]

In [27]:
[r1, r2, r3]

[['S', 'R', 'N'], [1, 1, 1], ['F', 'L', 'A']]

In [28]:
np.array([r1, r2, r3])

array([['S', 'R', 'N'],
       ['1', '1', '1'],
       ['F', 'L', 'A']], dtype='<U1')

In [30]:
print(np.array([r1, r2, r3])) # Os elementos devem possuir os mesmo tipos de dados

[['S' 'R' 'N']
 ['1' '1' '1']
 ['F' 'L' 'A']]
