In [ ]:
# Lists

In [1]:
l = [1, 2, 3, 4]

In [2]:
l

[1, 2, 3, 4]

In [3]:
# Arrays

In [4]:
import numpy as np

In [6]:
a = np.array(l)

In [7]:
a

array([1, 2, 3, 4])

In [8]:
# Devem armazenar os mesmos tipos de dados

In [17]:
b = np.array([1, 2, True, 69.9])

In [18]:
b

array([ 1. ,  2. ,  1. , 69.9])

In [11]:
# Todos os elementos foram convertidos para uma String / Float

In [16]:
# Listas & Arrays, por serem objetos, possuem uma série de funções

In [12]:
l.pop()

4

In [13]:
l

[1, 2, 3]

In [14]:
a.mean()

2.5

In [15]:
a

array([1, 2, 3, 4])

---

In [19]:
# Slicing Arrays

In [20]:
a

array([1, 2, 3, 4])

In [21]:
a[2:]

array([3, 4])

In [22]:
a[2:4]

array([3, 4])

In [23]:
b = a[2:4]

In [24]:
b

array([3, 4])

In [25]:
b[0]

3

In [26]:
b[:] = 111

In [27]:
a

array([  1,   2, 111, 111])

In [28]:
# Possuem a mesma referência

In [29]:
# Em listas, são criadas cópias diferentes

In [30]:
c = a.copy()

In [31]:
c

array([  1,   2, 111, 111])

---